// <auto-generated />
using LocalizationService.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocalizationService.DAL.Migrations
{
    [DbContext(typeof(LocalizationServiceDbContext))]
    partial class LocalizationServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocalizationService.DAL.Entities.LanguageEntity", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("LanguageCode");

                    b.HasIndex("LanguageCode")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("LocalizationService.DAL.Entities.LocalizationKeyEntity", b =>
                {
                    b.Property<string>("KeyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("KeyName");

                    b.HasIndex("KeyName")
                        .IsUnique();

                    b.ToTable("LocalizationKeys");
                });

            modelBuilder.Entity("LocalizationService.DAL.Entities.TranslationEntity", b =>
                {
                    b.Property<string>("LocalizationKey")
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("character varying(3)");

                    b.Property<string>("TranslationText")
                        .HasColumnType("text");

                    b.HasKey("LocalizationKey", "LanguageCode");

                    b.HasIndex("LanguageCode");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("LocalizationService.DAL.Entities.TranslationEntity", b =>
                {
                    b.HasOne("LocalizationService.DAL.Entities.LanguageEntity", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalizationService.DAL.Entities.LocalizationKeyEntity", "Localization")
                        .WithMany("Translations")
                        .HasForeignKey("LocalizationKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("LocalizationService.DAL.Entities.LanguageEntity", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("LocalizationService.DAL.Entities.LocalizationKeyEntity", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
